name : orbdot-lint
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:

  black-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install black
      run: pip install black

    - name: Check code with black
      run: black --check .

