name: PR checks

on:
  pull_request:
    branches: [master]

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Upgrade pip and install linters
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade packaging
      - name: Check version number
        run: python ./.github/workflows/check_version.py
